CREATE TABLE IF NOT EXISTS DEPARTMENTS (
    DEPT_NAME VARCHAR(20) NOT NULL,
    DEPT_NO VARCHAR(4) PRIMARY KEY NOT NULL
);

CREATE TABLE IF NOT EXISTS TITLES (
    TITLE TEXT NOT NULL,
    TITLE_ID VARCHAR(5) NOT NULL
);

CREATE TABLE IF NOT EXISTS EMPLOYEES (
    HIRE_DATE TEXT NOT NULL,
    BIRTH_DATE TEXT NOT NULL,
    FIRST_NAME TEXT NOT NULL,
    SEX VARCHAR(1) NOT NULL,
    EMP_TITLE_ID VARCHAR(5) NOT NULL,
    EMP_NO INTEGER PRIMARY KEY NOT NULL,
    FOREIGN KEY (EMP_TITLE_ID) REFERENCES TITLES (TITLE_ID) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS DEPT_EMP (
    EMP_NO INTEGER NOT NULL,
    DEPT_NO VARCHAR(4) NOT NULL,
    FOREIGN KEY (EMP_NO) REFERENCES EMPLOYEES (EMP_NO) ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (DEPT_NO) REFERENCES DEPARTMENTS (DEPT_NO) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS DEPT_MANAGER (
    EMP_NO INTEGER NOT NULL,
    DEPT_NO VARCHAR(4) NOT NULL,
    FOREIGN KEY (EMP_NO) REFERENCES EMPLOYEES (EMP_NO) ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (DEPT_NO) REFERENCES DEPARTMENTS (DEPT_NO) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS SALARIES (
    EMP_NO INTEGER NOT NULL,
    SALARY INTEGER NOT NULL,
    FOREIGN KEY (EMP_NO) REFERENCES EMPLOYEES (EMP_NO) ON DELETE CASCADE ON UPDATE CASCADE
);